name: plant_ecommerce
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  carousel_slider: ^4.2.1
  firebase_core: ^2.27.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  go_router: ^14.1.1
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/vectors/

  fonts:
    - family: TT Firs
      fonts:
        - asset: assets/fonts/TT Firs/TT Firs Neue Trial Light.ttf
          weight: 300
        - asset: assets/fonts/TT Firs/TT Firs Neue Trial Regular.ttf
          weight: 400
        - asset: assets/fonts/TT Firs/TT Firs Neue Trial Medium.ttf
          weight: 500
        - asset: assets/fonts/TT Firs/TT Firs Neue Trial DemiBold.ttf
          weight: 600
        - asset: assets/fonts/TT Firs/TT Firs Neue Trial Bold.ttf
          weight: 700
